ARDUINO_DIR		= /usr/share/arduino
ARDMK_DIR 		:= $(realpath ../tools/arduino-mk)
AVR_TOOLS_DIR	= /usr

BOARD_TAG		= leonardo
MONITOR_PORT	= /dev/ttyACM0
USER_LIB_PATH 	:= $(realpath ../libraries)
ARDUINO_LIBS 	= CmdMessenger EEPROM Encoder Mirf qp SPI 

include $(ARDMK_DIR)/Arduino.mk
