//****************************************************************************
// Model: pelican.qm
// File:  ./bsp.h
//
// This code has been generated by QM tool (see state-machine.com/qm).
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//****************************************************************************
//${.::bsp.h} ................................................................
#ifndef bsp_h
#define bsp_h

#include <avr/io.h>   // AVR I/O

// Outputs
#define GREEN_LED_ON()         (PORTB |= (1 << (5)))
#define GREEN_LED_OFF()        (PORTB &= ~(1 << (5)))
#define GREEN_LED_TOGGLE()     (PORTB ^= (1 << (5)))
#define WHITE_LED_ON()         (PORTC |= (1 << (7)))
#define WHITE_LED_OFF()        (PORTC &= ~(1 << (7)))
#define WHITE_LED_TOGGLE()     (PORTC ^= (1 << (7)))
#define AMBER2_LED_ON()        (PORTD |= (1 << (7)))
#define AMBER2_LED_OFF()       (PORTD &= ~(1 << (7)))
#define AMBER_LED_ON()         (PORTC |= (1 << (6)))
#define AMBER_LED_OFF()        (PORTC &= ~(1 << (6)))
#define AMBER_LED_TOGGLE()     (PORTC ^= (1 << (6)))
#define ENC_GREEN_LED_ON()     (PORTB |= (1 << (6)))
#define ENC_GREEN_LED_OFF()    (PORTB &= ~(1 << (6)))
#define ENC_GREEN_LED_TOGGLE() (PORTB ^= (1 << (6)))
#define ENC_RED_LED_ON()       (PORTB |= (1 << (7)))
#define ENC_RED_LED_OFF()      (PORTB &= ~(1 << (7)))

// Inputs
#define PBUTTON1_ON()     (PINF & 0x40)
#define PBUTTON2_ON()     (PINF & 0x20)
#define PBUTTON3_ON()     (PINF & 0x10)
#define PBUTTON4_ON()     (PINF & 0x02)
#define CALBUTTON_ON()    (PINF & 0x01)
#define PLAYSWITCH_ON()   (PIND & 0x10)
#define FREESWITCH_ON()   (PIND & 0x40)


#define IS_ODD(val) ((val) % 2 == 1)

// Sys timer tick per seconds
#define BSP_TICKS_PER_SEC    1024

void BSP_init(void);
void BSP_UpdateRxProxy(long pos);
long BSP_GetEncoder();
int  BSP_GetPot();

/////////////////////////////////////////////////////////////////////
// NOTE: The CPU clock frequency F_CPU is defined externally for each
// Arduino board

#endif  // bsp_h
